### ISSUE TITLE
Wrong text span in training

### ISSUE THREAD

**Issue by blackzaku** [knowledge-learning/ehealthkd-2019#5]
There is an incorrectly tokenized concept in the training set:

1616	22873 22874;22875 22877;22878 22880;22880 22881	Concept	5 al 10 %

There is no space between 10 and % in the input text file, reflected in the spans: 22878 22880;22880 22881. However, the raw text is wrong, as it has an space in between.

**Comment by apiad** [comment]
Hi @blackzaku , thanks for poiting that out. The reason for this is simple: when we generate the output file, we simply take all the text spans and join them by white space. Hence, since this concept has tokenized the `%` apart from the `10`, it gets joined by whitespace in the middle. 

However, this has no impact on the score, since these texts are only for reference when manually debugging your output, we do not actually use these texts to match anything or to score anything, is a mere visual indication so that we can quickly see if some spans are missing, etc. 

Anyway, we updated the `utils.py` file to take this detail into consideration, and re-checked that this keyphrase is now correctly tokenized. 

Thanks for pointing it out, and good luck in the competition !!
